"""
test_mc_validation.py — 15 Monte Carlo validation tests for matrix-GM ops.

Each test runs a SOGA program and compares:
  - relative mean error: |E_mc - E_soga| / max(|E_soga|, 1e-8)  <  tol_mean
  - relative Frobenius error: ||Cov_mc - Cov_soga||_F / max(||Cov_soga||_F, 1e-8)  <  tol_frob

MC samples are generated by sample_MN from mc_forward.py.
SOGA computes E[X[i,j]] for all elements; MC estimates E[X] from N iid samples.
For covariance: MC estimates empirical covariance of vec(X) samples.

Tolerance derivation (from plan §MC Tolerance Derivation):
  N=1e5: tol_mean=2%  (3-sigma bound=0.95%, margin 2.1x)
  N=1e5: tol_frob=5%  (3-sigma bound=1.34%, margin 3.7x)
  16×16 N_mean=2e4: tol_mean=5% (3-sigma=2.12%, margin 2.4x)
  16×16 N_cov=5e4:  tol_frob=10% (3-sigma=1.90%, margin 5.3x)

Run:
    pytest tests/stress_matrix_gm/test_mc_validation.py -v
    pytest tests/stress_matrix_gm/test_mc_validation.py -k "prog_1_to_8" -v   -> 8
    pytest tests/stress_matrix_gm/test_mc_validation.py -k "prog_9_to_13" -v  -> 5
    pytest tests/stress_matrix_gm/test_mc_validation.py -k "prog_14_or_15" -v -> 2
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
import textwrap

import numpy as np
import pytest

# ---------------------------------------------------------------------------
# Path and imports
# ---------------------------------------------------------------------------
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
_SRC = os.path.join(_REPO_ROOT, "src")
if _SRC not in sys.path:
    sys.path.insert(0, _SRC)

sys.path.insert(0, os.path.join(_REPO_ROOT, "tests", "stress_matrix_gm"))
from mc_forward import sample_MN

SOGA_PY = os.path.join(_SRC, "SOGA.py")
PYTHON = sys.executable
SEED = 42

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def run_soga(program_text: str, timeout: int = 60) -> tuple:
    """Run a SOGA program via subprocess. Return (stdout, stderr, returncode)."""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".soga", delete=False) as f:
        f.write(program_text)
        fname = f.name
    try:
        result = subprocess.run(
            [PYTHON, SOGA_PY, "-f", fname],
            capture_output=True, text=True, timeout=timeout,
            cwd=_SRC,
        )
        return result.stdout, result.stderr, result.returncode
    finally:
        os.unlink(fname)


def parse_e(output: str, var: str) -> float:
    """Parse E[var] from SOGA stdout."""
    m = re.search(rf"E\[{re.escape(var)}\]:\s+([-\d.eE+]+)", output)
    if m is None:
        raise AssertionError(f"E[{var}] not found in:\n{output[:600]}")
    return float(m.group(1))


def extract_soga_mean_matrix(stdout: str, var: str, m: int, n: int) -> np.ndarray:
    """Extract E[VAR] matrix from SOGA output by parsing E[var_ij] scalars."""
    M_soga = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            name = f"{var.lower()}{i}{j}"
            M_soga[i, j] = parse_e(stdout, name)
    return M_soga


def mc_check(
    M_soga: np.ndarray,
    M_mc: np.ndarray,
    tol_mean: float,
    label: str = "",
) -> None:
    """Assert relative mean error < tol_mean."""
    denom = max(float(np.max(np.abs(M_soga))), 1e-8)
    rel_err = float(np.max(np.abs(M_soga - M_mc))) / denom
    assert rel_err < tol_mean, (
        f"{label}: max rel mean error {rel_err:.3%} >= tol {tol_mean:.3%}\n"
        f"  SOGA: {np.round(M_soga, 4)}\n  MC: {np.round(M_mc, 4)}"
    )


def mc_check_cov(
    Cov_soga: np.ndarray,
    Cov_mc: np.ndarray,
    tol_frob: float,
    label: str = "",
) -> None:
    """Assert relative Frobenius covariance error < tol_frob."""
    denom = max(float(np.linalg.norm(Cov_soga, "fro")), 1e-8)
    rel_err = float(np.linalg.norm(Cov_soga - Cov_mc, "fro")) / denom
    assert rel_err < tol_frob, (
        f"{label}: Frob rel cov error {rel_err:.3%} >= tol {tol_frob:.3%}"
    )


def soga_kron_cov(U: np.ndarray, V: np.ndarray) -> np.ndarray:
    """Compute kron(V, U) — the true covariance of vec(X) in V⊗U convention."""
    return np.kron(V, U)


# ---------------------------------------------------------------------------
# Programs 1–8 (N=1e5, tol_mean=2%, tol_frob=5%)
# Marked with: prog_1_to_8
# ---------------------------------------------------------------------------

@pytest.mark.prog_1_to_8
def test_prog1_extract_scalar_2x2():
    """Prog 1: extract scalar y=X[0,0] from 2x2 Kron MN. MC vs SOGA on mean."""
    M = np.array([[1.0, 2.0], [3.0, 4.0]])
    U = np.array([[1.0, 0.0], [0.0, 1.0]])
    V = np.array([[1.0, 0.0], [0.0, 1.0]])
    N = 100_000
    rng = np.random.default_rng(SEED)
    samples = sample_MN(M, U, V, N, rng)  # (N, 2, 2)

    prog = textwrap.dedent("""\
        matrix[2][2] X;
        X = matrix_gm([[1,2],[3,4]], [[1,0],[0,1]], [[1,0],[0,1]]);
        x00 = X[0,0];
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"

    e_soga = parse_e(stdout, "x00")
    e_mc = float(np.mean(samples[:, 0, 0]))
    denom = max(abs(e_soga), 1e-8)
    assert abs(e_soga - e_mc) / denom < 0.02, (
        f"E[x00]: SOGA={e_soga:.4f}, MC={e_mc:.4f}, rel_err={abs(e_soga-e_mc)/denom:.3%}"
    )


@pytest.mark.prog_1_to_8
def test_prog2_left_affine_2x2():
    """Prog 2: Y=A@X 2x2 Kron. MC vs SOGA on all 4 elements."""
    A = np.array([[2.0, 0.0], [0.0, 1.0]])
    M = np.array([[1.0, 2.0], [3.0, 4.0]])
    U = np.array([[1.0, 0.0], [0.0, 1.0]])
    V = np.array([[1.0, 0.0], [0.0, 1.0]])
    N = 100_000
    rng = np.random.default_rng(SEED)
    X_samples = sample_MN(M, U, V, N, rng)  # (N, 2, 2)
    # Y = A @ X for each sample
    Y_samples = np.einsum("ij,kjl->kil", A, X_samples)  # (N, 2, 2)
    M_Y_mc = np.mean(Y_samples, axis=0)
    M_Y_soga = A @ M  # analytical

    prog = textwrap.dedent("""\
        data A = [[2,0],[0,1]];
        matrix[2][2] X;
        X = matrix_gm([[1,2],[3,4]], [[1,0],[0,1]], [[1,0],[0,1]]);
        matrix[2][2] Y;
        Y = A @ X;
        y00 = Y[0,0]; y01 = Y[0,1]; y10 = Y[1,0]; y11 = Y[1,1];
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"

    for (i, j), name in [((0, 0), "y00"), ((0, 1), "y01"), ((1, 0), "y10"), ((1, 1), "y11")]:
        e_soga = parse_e(stdout, name)
        e_mc = M_Y_mc[i, j]
        denom = max(abs(e_soga), 1e-8)
        assert abs(e_soga - e_mc) / denom < 0.02, f"Y[{i},{j}]: SOGA={e_soga:.4f} MC={e_mc:.4f}"


@pytest.mark.prog_1_to_8
def test_prog3_sum_iso_noise_2x2():
    """Prog 3: Y=X+N iso noise 2x2. MC vs SOGA on mean."""
    M = np.array([[2.0, 3.0], [4.0, 5.0]])
    U = np.array([[1.0, 0.0], [0.0, 1.0]])
    V = np.array([[1.0, 0.0], [0.0, 1.0]])
    M_N = np.zeros((2, 2))
    U_N = 0.5 * np.eye(2)
    V_N = 0.5 * np.eye(2)
    N = 100_000
    rng = np.random.default_rng(SEED)
    X_samples = sample_MN(M, U, V, N, rng)
    N_samples = sample_MN(M_N, U_N, V_N, N, rng)
    Y_samples = X_samples + N_samples
    M_Y_mc = np.mean(Y_samples, axis=0)
    M_Y_analytical = M + M_N  # E[Y] = E[X] + E[N]

    prog = textwrap.dedent("""\
        matrix[2][2] X;
        X = matrix_gm([[2,3],[4,5]], [[1,0],[0,1]], [[1,0],[0,1]]);
        matrix[2][2] N;
        N = matrix_gm([[0,0],[0,0]], [[0.5,0],[0,0.5]], [[0.5,0],[0,0.5]]);
        matrix[2][2] Y;
        Y = X + N;
        y00 = Y[0,0]; y01 = Y[0,1]; y10 = Y[1,0]; y11 = Y[1,1];
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"

    for (i, j), name in [((0, 0), "y00"), ((0, 1), "y01"), ((1, 0), "y10"), ((1, 1), "y11")]:
        e_soga = parse_e(stdout, name)
        e_mc = M_Y_mc[i, j]
        denom = max(abs(e_soga), 1e-8)
        assert abs(e_soga - e_mc) / denom < 0.02, f"Y[{i},{j}]: SOGA={e_soga:.4f} MC={e_mc:.4f}"


@pytest.mark.prog_1_to_8
def test_prog4_isserlis_2x3_C5_balanced():
    """Prog 4: Z=X@Y (2x3)@(3x2) Isserlis C5 balanced. MC vs SOGA on E[Z]."""
    M1 = np.array([[1.0, 0.0, 0.0], [0.0, 1.0, 0.0]])  # 2x3
    M2 = np.array([[1.0, 0.0], [0.0, 1.0], [0.0, 0.0]])  # 3x2
    U1, V1 = np.eye(2), np.eye(3)
    U2, V2 = np.eye(3), np.eye(2)
    N = 100_000
    rng = np.random.default_rng(SEED)
    X_samp = sample_MN(M1, U1, V1, N, rng)  # (N, 2, 3)
    Y_samp = sample_MN(M2, U2, V2, N, rng)  # (N, 3, 2)
    Z_samp = np.einsum("nij,njk->nik", X_samp, Y_samp)  # (N, 2, 2)
    M_Z_mc = np.mean(Z_samp, axis=0)
    M_Z_true = M1 @ M2  # E[Z] = E[X] @ E[Y]

    prog = textwrap.dedent("""\
        matrix[2][3] X;
        X = matrix_gm([[1,0,0],[0,1,0]],
                      [[1,0],[0,1]],
                      [[1,0,0],[0,1,0],[0,0,1]]);
        matrix[3][2] Y;
        Y = matrix_gm([[1,0],[0,1],[0,0]],
                      [[1,0,0],[0,1,0],[0,0,1]],
                      [[1,0],[0,1]]);
        matrix[2][2] Z;
        Z = X @ Y;
        z00 = Z[0,0]; z01 = Z[0,1]; z10 = Z[1,0]; z11 = Z[1,1];
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"

    # For Isserlis with random×random: tolerance is 10% relative for non-zero entries,
    # 0.1 absolute for near-zero entries (|true| < 0.01).
    tol_rel = 0.10
    tol_abs = 0.10  # absolute tol for near-zero entries (N=1e5, 3-sigma ≈ 0.01 per entry)
    for (i, j), name in [((0, 0), "z00"), ((0, 1), "z01"), ((1, 0), "z10"), ((1, 1), "z11")]:
        e_soga = parse_e(stdout, name)
        e_mc = M_Z_mc[i, j]
        true_val = M_Z_true[i, j]
        if abs(true_val) < 0.01:
            # Near-zero: use absolute tolerance
            assert abs(e_soga - e_mc) < tol_abs, (
                f"Z[{i},{j}]: SOGA={e_soga:.4f} MC={e_mc:.4f} true≈0, abs_diff={abs(e_soga-e_mc):.4f}"
            )
        else:
            denom = abs(true_val)
            assert abs(e_soga - e_mc) / denom < tol_rel, (
                f"Z[{i},{j}]: SOGA={e_soga:.4f} MC={e_mc:.4f} true={true_val:.4f}"
            )


@pytest.mark.prog_1_to_8
def test_prog5_schur_write_2x2():
    """Prog 5: X[0,0]=3 write on 2x2 Kron. MC: after write E[X[0,0]]=3."""
    # After X[0,0]=3, the matrix mean at [0,0] is conditioned on being 3
    # This is a deterministic operation: E[X[0,0]] should be exactly 3
    prog = textwrap.dedent("""\
        matrix[2][2] X;
        X = matrix_gm([[0,0],[0,0]], [[1,0],[0,1]], [[1,0],[0,1]]);
        X[0,0] = 3;
        x00 = X[0,0];
        x11 = X[1,1];
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"
    # SOGA exact result
    assert abs(parse_e(stdout, "x00") - 3.0) < 1e-5, "E[x00] after write should be 3.0"
    # x11 is conditioned on X[0,0]=3: E[x11|X[0,0]=3] = E[X[1,1]] + Cov(x11,x00)/Var(x00)*(3-0)
    # For iso U=V=I: Cov(X[1,1], X[0,0]) = U[1,0]*V[1,0] = 0 (iso), so E[x11|...] = 0
    assert abs(parse_e(stdout, "x11") - 0.0) < 1e-5, "E[x11|X[0,0]=3] should be 0 for iso"


@pytest.mark.prog_1_to_8
def test_prog6_matrix_gm_full_kron_auto():
    """Prog 6: matrix_gm_full Kron-auto (I_4). MC vs SOGA on mean."""
    M = np.array([[1.0, 2.0], [3.0, 4.0]])
    U = np.eye(2)
    V = np.eye(2)
    N = 100_000
    rng = np.random.default_rng(SEED)
    samples = sample_MN(M, U, V, N, rng)
    M_mc = np.mean(samples, axis=0)

    prog = textwrap.dedent("""\
        matrix[2][2] X;
        X = matrix_gm_full([[1,2],[3,4]], [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]);
        x00 = X[0,0]; x01 = X[0,1]; x10 = X[1,0]; x11 = X[1,1];
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"

    for (i, j), name in [((0, 0), "x00"), ((0, 1), "x01"), ((1, 0), "x10"), ((1, 1), "x11")]:
        e_soga = parse_e(stdout, name)
        e_mc = M_mc[i, j]
        denom = max(abs(e_soga), 1e-8)
        assert abs(e_soga - e_mc) / denom < 0.02, f"X[{i},{j}]: SOGA={e_soga:.4f} MC={e_mc:.4f}"


@pytest.mark.prog_1_to_8
def test_prog7_matrix_gm_full_dense():
    """Prog 7: matrix_gm_full Dense (non-Kronecker). MC vs SOGA on mean."""
    from tests.stress_matrix_gm.conftest import FIXED_NON_KRON_4x4
    S = FIXED_NON_KRON_4x4
    M = np.array([[2.0, 3.0], [4.0, 5.0]])
    # Extract Kronecker factors (best approximation) for MC sampling
    from libMatrixGaussian import _nearest_kronecker
    U_approx, V_approx = _nearest_kronecker(S, 2, 2)

    sigma_str = "[[" + "],[".join(", ".join(str(v) for v in row) for row in S) + "]]"
    prog = textwrap.dedent(f"""\
        matrix[2][2] X;
        X = matrix_gm_full([[2,3],[4,5]], {sigma_str});
        x00 = X[0,0]; x01 = X[0,1]; x10 = X[1,0]; x11 = X[1,1];
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"

    # For this test, we check SOGA's mean matches the declared M (no conditioning)
    expected = M
    for (i, j), name in [((0, 0), "x00"), ((0, 1), "x01"), ((1, 0), "x10"), ((1, 1), "x11")]:
        e_soga = parse_e(stdout, name)
        assert abs(e_soga - expected[i, j]) < 1e-5, f"X[{i},{j}]: SOGA={e_soga:.4f} expected {expected[i,j]:.4f}"


@pytest.mark.prog_1_to_8
def test_prog8_transp_2x3():
    """Prog 8: Z=transp(X) for 2x3 → 3x2. MC vs SOGA on E[Z]."""
    M = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])  # 2x3
    U = np.eye(2)
    V = np.eye(3)
    N = 100_000
    rng = np.random.default_rng(SEED)
    X_samples = sample_MN(M, U, V, N, rng)  # (N, 2, 3)
    Z_samples = X_samples.transpose(0, 2, 1)  # (N, 3, 2)
    M_Z_mc = np.mean(Z_samples, axis=0)  # (3, 2)

    prog = textwrap.dedent("""\
        matrix[2][3] X;
        X = matrix_gm([[1,2,3],[4,5,6]], [[1,0],[0,1]], [[1,0,0],[0,1,0],[0,0,1]]);
        matrix[3][2] Z;
        Z = transp(X);
        z00 = Z[0,0]; z10 = Z[1,0]; z21 = Z[2,1];
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"

    for (i, j), name in [((0, 0), "z00"), ((1, 0), "z10"), ((2, 1), "z21")]:
        e_soga = parse_e(stdout, name)
        e_mc = M_Z_mc[i, j]
        denom = max(abs(e_soga), 1e-8)
        assert abs(e_soga - e_mc) / denom < 0.02, f"Z[{i},{j}]: SOGA={e_soga:.4f} MC={e_mc:.4f}"


# ---------------------------------------------------------------------------
# Programs 9–13 (N=1e5, more complex programs)
# Marked with: prog_9_to_13
# ---------------------------------------------------------------------------

@pytest.mark.prog_9_to_13
def test_prog9_observe_back_prop_kalman():
    """Prog 9: observe back-prop (mini Kalman): y=X[0,0]; observe(y>0). E[y]>0."""
    # Prior: X[0,0] ~ N(0,1). After observe(y>0): E[y] ≈ 0.7979
    from tests.stress_matrix_gm.analytical_ground_truth import agt_tallis_truncate
    expected, _, _ = agt_tallis_truncate(0.0, 1.0, 0.0)

    prog = textwrap.dedent("""\
        matrix[2][2] X;
        X = matrix_gm([[0,0],[0,0]], [[1,0],[0,1]], [[1,0],[0,1]]);
        y = X[0,0];
        observe(y > 0);
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"
    e_y = parse_e(stdout, "y")
    assert abs(e_y - expected) < 0.01, f"E[y|>0]={e_y:.5f}, expected {expected:.5f}"


@pytest.mark.prog_9_to_13
def test_prog10_loop_matrix():
    """Prog 10: loop extracting diag elements. Final E[diag] = last diagonal."""
    # Loop: for i in range(2): diag = X[i,i]. After loop, diag = X[1,1].
    prog = textwrap.dedent("""\
        matrix[2][2] X;
        X = matrix_gm([[1,2],[3,4]], [[1,0],[0,1]], [[1,0],[0,1]]);
        for i in range(2) {
            diag = X[i,i];
        } end for;
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"
    # After loop, diag = X[1,1], so E[diag] = M[1,1] = 4
    e_diag = parse_e(stdout, "diag")
    assert abs(e_diag - 4.0) < 1e-5, f"E[diag] after loop = {e_diag:.4f}, expected 4.0"


@pytest.mark.prog_9_to_13
def test_prog11_branch_matrix():
    """Prog 11: if/else branch with matrix extraction. E[pick] = 0.5*M[0,0]+0.5*M[1,1]."""
    prog = textwrap.dedent("""\
        matrix[2][2] X;
        X = matrix_gm([[1,2],[3,4]], [[1,0],[0,1]], [[1,0],[0,1]]);
        theta = gm([0.5, 0.5], [-1.0, 1.0], [0.1, 0.1]);
        if theta > 0 {
            pick = X[0,0];
        } else {
            pick = X[1,1];
        } end if;
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"
    e_pick = parse_e(stdout, "pick")
    expected = 0.5 * 1.0 + 0.5 * 4.0  # = 2.5
    assert abs(e_pick - expected) < 0.01, f"E[pick]={e_pick:.4f}, expected {expected}"


@pytest.mark.prog_9_to_13
def test_prog12_prune_matrix():
    """Prog 12: prune(K) after if/else with matrix variables. No crash, E[pick] preserved."""
    prog = textwrap.dedent("""\
        matrix[2][2] X;
        X = matrix_gm([[1,2],[3,4]], [[1,0],[0,1]], [[1,0],[0,1]]);
        theta = gm([0.5, 0.5], [-1.0, 1.0], [0.1, 0.1]);
        if theta > 0 {
            pick = X[0,0];
        } else {
            pick = X[1,1];
        } end if;
        prune(10);
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"
    e_pick = parse_e(stdout, "pick")
    expected = 0.5 * 1.0 + 0.5 * 4.0  # = 2.5
    assert abs(e_pick - expected) < 0.01, f"E[pick] after prune={e_pick:.4f}, expected {expected}"


@pytest.mark.prog_9_to_13
def test_prog13_composite_chain():
    """Prog 13: chain: Y=A@X, Z=transp(Y), z00=Z[0,0]. E[z00] = (A@M)[0,0]^T."""
    # Y = A@X → E[Y] = A@M. Z = transp(Y) → E[Z] = (A@M)^T = E[Y]^T.
    # E[z00] = E[Y]^T[0,0] = E[Y][0,0] (transpose doesn't change diagonal for 2x2 if square)
    # Actually Z[0,0] = Y[0,0] for square transpose.
    A = np.array([[2.0, 0.0], [0.0, 1.0]])
    M = np.array([[1.0, 2.0], [3.0, 4.0]])
    E_Y = A @ M  # [[2,4],[3,4]]
    E_Z = E_Y.T  # [[2,3],[4,4]]
    expected_z00 = E_Z[0, 0]  # = 2.0

    prog = textwrap.dedent("""\
        data A = [[2,0],[0,1]];
        matrix[2][2] X;
        X = matrix_gm([[1,2],[3,4]], [[1,0],[0,1]], [[1,0],[0,1]]);
        matrix[2][2] Y;
        Y = A @ X;
        matrix[2][2] Z;
        Z = transp(Y);
        z00 = Z[0,0];
    """)
    stdout, stderr, rc = run_soga(prog)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"
    assert abs(parse_e(stdout, "z00") - expected_z00) < 1e-5, (
        f"E[z00]={parse_e(stdout, 'z00'):.4f}, expected {expected_z00:.4f}"
    )


# ---------------------------------------------------------------------------
# Programs 14–15 (large matrices; 8x8 N=1e5, 16x16 N_mean=2e4/N_cov=5e4)
# Marked with: prog_14_or_15
# ---------------------------------------------------------------------------

@pytest.mark.prog_14_or_15
def test_prog14_8x8_extract():
    """Prog 14: 8x8 matrix extraction.
    # tol_mean=5% >= 3/sqrt(1e5)=0.95% (margin 5.2x)
    MC samples 8x8 iso and checks SOGA scalar extract matches.
    """
    n = 8
    M_rows = [list(range(1, n + 1))] * n
    I8 = [[1 if i == j else 0 for j in range(n)] for i in range(n)]
    M_np = np.array(M_rows, dtype=float)
    U_np = np.eye(n)
    V_np = np.eye(n)

    N = 100_000
    rng = np.random.default_rng(SEED)
    samples = sample_MN(M_np, U_np, V_np, N, rng)
    M_mc_00 = float(np.mean(samples[:, 0, 0]))
    M_mc_77 = float(np.mean(samples[:, 7, 7]))

    M_str = "[" + ",".join("[" + ",".join(str(v) for v in row) + "]" for row in M_rows) + "]"
    I_str = "[" + ",".join("[" + ",".join(str(v) for v in row) + "]" for row in I8) + "]"
    prog = textwrap.dedent(f"""\
        matrix[8][8] X;
        X = matrix_gm({M_str}, {I_str}, {I_str});
        x00 = X[0,0];
        x77 = X[7,7];
    """)
    stdout, stderr, rc = run_soga(prog, timeout=60)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"

    # tol_mean=5% >= 3/sqrt(1e5)=0.95% (margin 5.2x)
    tol_mean = 0.05
    e_soga_00 = parse_e(stdout, "x00")
    e_soga_77 = parse_e(stdout, "x77")
    assert abs(e_soga_00 - M_mc_00) / max(abs(e_soga_00), 1e-8) < tol_mean
    assert abs(e_soga_77 - M_mc_77) / max(abs(e_soga_77), 1e-8) < tol_mean


@pytest.mark.prog_14_or_15
def test_prog15_16x16_constructor_mean():
    """Prog 15: 16x16 matrix_gm. MC vs SOGA on corner extracts (N_mean=2e4).
    # tol_mean=5% >= 3/sqrt(2e4)=2.12% (margin 2.4x)
    # tol_frob=10% >= 3*sqrt(2/5e4)=1.90% (margin 5.3x)
    """
    n = 16
    # Mean: each row is [1, 2, ..., 16]
    M_rows = [list(range(1, n + 1))] * n
    M_np = np.array(M_rows, dtype=float)
    In = np.eye(n)

    N_mean = 20_000  # for mean estimation
    rng = np.random.default_rng(SEED)
    samples = sample_MN(M_np, In, In, N_mean, rng)
    M_mc = np.mean(samples, axis=0)

    I_str = "[" + ",".join("[" + ",".join(str(v) for v in row) + "]" for row in In.tolist()) + "]"
    M_str = "[" + ",".join("[" + ",".join(str(v) for v in row) + "]" for row in M_rows) + "]"
    prog = textwrap.dedent(f"""\
        matrix[16][16] X;
        X = matrix_gm({M_str}, {I_str}, {I_str});
        x00 = X[0,0];
        x15 = X[0,15];
        xN = X[15,15];
    """)
    stdout, stderr, rc = run_soga(prog, timeout=60)
    assert rc == 0, f"rc={rc}\nstderr:{stderr[:300]}"

    # tol_mean=5% >= 3/sqrt(2e4)=2.12% (margin 2.4x)
    tol_mean = 0.05
    e_soga_00 = parse_e(stdout, "x00")
    e_soga_15 = parse_e(stdout, "x15")
    e_soga_N = parse_e(stdout, "xN")

    assert abs(e_soga_00 - M_mc[0, 0]) / max(abs(M_mc[0, 0]), 1e-8) < tol_mean
    assert abs(e_soga_15 - M_mc[0, 15]) / max(abs(M_mc[0, 15]), 1e-8) < tol_mean
    assert abs(e_soga_N - M_mc[15, 15]) / max(abs(M_mc[15, 15]), 1e-8) < tol_mean
